import { Card } from './types';

export const ALL_CARDS: Card[] = [
  // Card 1
  {
    id: 1,
    deck: 'SCENE_ON_HAI',
    title: 'RAJA HAS ARRIVED',
    urduTitle: 'راجہ صاحب آ گئے',
    description: 'A Raja has decided your property looks interesting.',
    actionText: 'If you have a house/hotel: Remove 1 building. If no buildings: Transfer property to a random player.',
    illustration: '👑',
    actionType: 'REMOVE_BUILDING_OR_TRANSFER',
  },
  // Card 2
  {
    id: 2,
    deck: 'SCENE_ON_HAI',
    title: 'KHOKHAR ROYALTY',
    urduTitle: 'کھوکھر رائلٹی',
    description: 'Royalty collection has begun.',
    actionText: 'COLLECT Rs 50 FROM EVERY PLAYER',
    illustration: '🏰',
    actionType: 'COLLECT_FROM_ALL',
    amount: 50,
  },
  // Card 3
  {
    id: 3,
    deck: 'SCENE_ON_HAI',
    title: 'POLICE BRIBING',
    urduTitle: 'چائے پانی',
    description: 'You have been stopped for absolutely no reason.',
    actionText: 'PAY Rs 50 AND CONTINUE',
    illustration: '👮',
    actionType: 'PAY_TO_BANK',
    amount: 50,
  },
  // Card 4
  {
    id: 4,
    deck: 'SCENE_ON_HAI',
    title: 'MET A LAHORI',
    urduTitle: 'لاہوری سے راستہ پوچھا',
    description: 'You asked a Lahori for directions. You went the wrong way.',
    actionText: 'GO DIRECTLY TO THANA (JAIL)',
    illustration: '🧭',
    actionType: 'GO_TO_JAIL',
  },
  // Card 5
  {
    id: 5,
    deck: 'SCENE_ON_HAI',
    title: 'ARMY CHECKPOINT',
    urduTitle: 'سیکیورٹی چیک پوسٹ',
    description: '"For security reasons."',
    actionText: 'EVERY OTHER PLAYER PAYS Rs 20 TO THE BANK',
    illustration: '🪖',
    actionType: 'PAY_TO_BANK', // handled in card engine for others
    amount: 20,
  },
  // Card 6
  {
    id: 6,
    deck: 'PAKISTAN_ZINDABAD',
    title: 'FBR HAS ENTERED THE CHAT',
    urduTitle: 'ایف بی آر نوٹس',
    description: "Nobody knows why they're here.",
    actionText: 'PAY Rs 100 TO THE BANK',
    illustration: '📑',
    actionType: 'PAY_TO_BANK',
    amount: 100,
  },
  // Card 7
  {
    id: 7,
    deck: 'PAKISTAN_ZINDABAD',
    title: 'PATWARI PROBLEM',
    urduTitle: 'پٹواری کا چکر',
    description: 'Your paperwork has suddenly become complicated.',
    actionText: 'PAY Rs 50 TO SORT OUT INTAQAAL',
    illustration: '📜',
    actionType: 'PAY_TO_BANK',
    amount: 50,
  },
  // Card 8
  {
    id: 8,
    deck: 'SCENE_ON_HAI',
    title: 'WEDDING SEASON',
    urduTitle: 'شادیوں کا سیزن',
    description: "Three weddings this month. Your wallet didn't survive.",
    actionText: 'PAY Rs 100',
    illustration: '🎉',
    actionType: 'PAY_TO_BANK',
    amount: 100,
  },
  // Card 9
  {
    id: 9,
    deck: 'PAKISTAN_ZINDABAD',
    title: 'DHA DEVELOPMENT',
    urduTitle: 'ڈی ایچ اے ترقیاتی فنڈ',
    description: 'Your neighborhood is suddenly "premium."',
    actionText: 'COLLECT Rs 100 BONUS',
    illustration: '🏗️',
    actionType: 'MONEY_ADD',
    amount: 100,
  },
  // Card 10
  {
    id: 10,
    deck: 'PAKISTAN_ZINDABAD',
    title: 'POLITICAL CONNECTION',
    urduTitle: 'سیاسی سفارش',
    description: 'You know someone who knows someone.',
    actionText: 'COLLECT Rs 100',
    illustration: '🤝',
    actionType: 'MONEY_ADD',
    amount: 100,
  },
  // Card 11
  {
    id: 11,
    deck: 'SCENE_ON_HAI',
    title: 'BIJLI KA BILL',
    urduTitle: 'بجلی کا بل',
    description: 'You forgot to check the meter. Heavy surcharge added!',
    actionText: 'PAY Rs 75',
    illustration: '⚡',
    actionType: 'PAY_TO_BANK',
    amount: 75,
  },
  // Card 12
  {
    id: 12,
    deck: 'SCENE_ON_HAI',
    title: 'LOAD SHEDDING',
    urduTitle: 'لوڈ شیڈنگ',
    description: 'The lights are gone. Generator broke down.',
    actionText: 'MISS YOUR NEXT TURN',
    illustration: '🕯️',
    actionType: 'MISS_TURN',
  },
  // Card 13
  {
    id: 13,
    deck: 'SCENE_ON_HAI',
    title: 'BIRYANI DEBATE',
    urduTitle: 'بریانی پر بحث',
    description: 'Karachi and Lahore have started arguing over Aloo vs Elaichi.',
    actionText: 'ROLL DICE: ODD = PAY Rs 50, EVEN = COLLECT Rs 50',
    illustration: '🍚',
    actionType: 'BIRYANI_DICE_ROLL',
  },
  // Card 14
  {
    id: 14,
    deck: 'SCENE_ON_HAI',
    title: 'CHAI FOR EVERYONE',
    urduTitle: 'سب کے لیے چائے',
    description: 'You ordered chai and parathas for the whole table.',
    actionText: 'PAY Rs 20 TO EVERY OTHER PLAYER',
    illustration: '☕',
    actionType: 'PAY_TO_ALL',
    amount: 20,
  },
  // Card 15
  {
    id: 15,
    deck: 'SCENE_ON_HAI',
    title: 'TRAFFIC POLICE',
    urduTitle: 'وارڈن کا چالان',
    description: 'You made a U-turn. The road apparently had no U-turn.',
    actionText: 'PAY Rs 50 FINE',
    illustration: '🛑',
    actionType: 'PAY_TO_BANK',
    amount: 50,
  },
  // Card 16
  {
    id: 16,
    deck: 'SCENE_ON_HAI',
    title: 'NADRA QUEUE',
    urduTitle: 'نادرا کی لائن',
    description: "Your number is 47. They're currently serving number 12. Server is down.",
    actionText: 'MISS YOUR NEXT TURN',
    illustration: '🪪',
    actionType: 'MISS_TURN',
  },
  // Card 17
  {
    id: 17,
    deck: 'PAKISTAN_ZINDABAD',
    title: 'COUSIN IN GOVERNMENT',
    urduTitle: 'سرکاری رشتہ دار',
    description: 'Your cousin "knows a guy" in the high court.',
    actionText: 'GET OUT OF THANA FREE (Hold card until used)',
    illustration: '⚖️',
    actionType: 'GET_OUT_OF_JAIL',
  },
  // Card 18
  {
    id: 18,
    deck: 'SCENE_ON_HAI',
    title: 'MEHMAAN AA GAYE',
    urduTitle: 'مہمان آ گئے',
    description: 'Six relatives arrived unexpectedly from the village.',
    actionText: 'PAY Rs 50 FOR MITHAI & COLD DRINKS',
    illustration: '🧁',
    actionType: 'PAY_TO_BANK',
    amount: 50,
  },
  // Card 19
  {
    id: 19,
    deck: 'PAKISTAN_ZINDABAD',
    title: 'EID ENVELOPE',
    urduTitle: 'عیدی کا لفافہ',
    description: 'A generous rich overseas uncle remembered you exist.',
    actionText: 'COLLECT Rs 100 EIDI',
    illustration: '✉️',
    actionType: 'MONEY_ADD',
    amount: 100,
  },
  // Card 20
  {
    id: 20,
    deck: 'SCENE_ON_HAI',
    title: 'PETROL PRICES',
    urduTitle: 'پیٹرول کی قیمتیں',
    description: 'Petrol prices went up at midnight again. Obviously.',
    actionText: 'PAY Rs 50',
    illustration: '⛽',
    actionType: 'PAY_TO_BANK',
    amount: 50,
  },
  // Card 21
  {
    id: 21,
    deck: 'SCENE_ON_HAI',
    title: "FATHER'S CITY CAR",
    urduTitle: 'ابو کی گاڑی',
    description: 'You took your father\'s car without asking. You hit a pole.',
    actionText: 'PAY Rs 100 FOR DENTING & PAINTING',
    illustration: '🚗',
    actionType: 'PAY_TO_BANK',
    amount: 100,
  },
  // Card 22
  {
    id: 22,
    deck: 'SCENE_ON_HAI',
    title: 'QUETTA CAFÉ — ISLAMABAD',
    urduTitle: 'کوئٹہ کیفے اسلام آباد',
    description: 'You went to Quetta Café in Islamabad for "a quick chai." Three hours later you\'re in another dimension.',
    actionText: 'GO TO NEW YORK (Fly 10 spaces forward!)',
    illustration: '✈️',
    actionType: 'SPECIAL_NEW_YORK',
    amount: 10,
  },
  // Card 23
  {
    id: 23,
    deck: 'SCENE_ON_HAI',
    title: 'GIRLFRIEND SCAMMED YOU',
    urduTitle: 'آن لائن اسکیم',
    description: 'Your girlfriend convinced you to EasyPaisa your last Rs 50, then blocked you.',
    actionText: 'PAY Rs 50',
    illustration: '💔',
    actionType: 'PAY_TO_BANK',
    amount: 50,
  },
  // Card 24
  {
    id: 24,
    deck: 'SCENE_ON_HAI',
    title: 'FATHER HAS HAD ENOUGH',
    urduTitle: 'ابو ناراض',
    description: 'Your father discovered you are unemployed. "Beta, ghar se nikal jao."',
    actionText: 'PAY Rs 100 FOR TEMPORARY LIVING EXPENSES',
    illustration: '🚪',
    actionType: 'PAY_TO_BANK',
    amount: 100,
  },
  // Card 25
  {
    id: 25,
    deck: 'PAKISTAN_ZINDABAD',
    title: 'ARMY KID SPECIAL PRIVILEGE',
    urduTitle: 'فوجی کوٹہ',
    description: "You're an Army kid. VIP green lane unlocked.",
    actionText: 'MOVE DIRECTLY TO START & COLLECT Rs 200',
    illustration: '🎖️',
    actionType: 'MOVE_TO',
    targetPosition: 0,
    amount: 200,
  },
  // Card 26
  {
    id: 26,
    deck: 'SCENE_ON_HAI',
    title: 'GOLD LEAF BREAK',
    urduTitle: 'گولڈ لیف بریک',
    description: 'You went outside with the boys for a quick smoke and tea.',
    actionText: 'PAY Rs 20',
    illustration: '🚬',
    actionType: 'PAY_TO_BANK',
    amount: 20,
  },
  // Card 27 - Building Assessment
  {
    id: 27,
    deck: 'PAKISTAN_ZINDABAD',
    title: 'ARMY CAME FOR INSPECTION',
    urduTitle: 'کیمپ انوسٹی گیشن',
    description: 'The Army came by, liked your homes, and now wants their share.',
    actionText: 'PAY Rs 25 PER HOUSE & Rs 50 PER HOTEL',
    illustration: '🪖',
    actionType: 'PER_BUILDING_ASSESSMENT',
    perHouseCost: 25,
    perHotelCost: 50,
  },
  // Card 28 - Building Assessment
  {
    id: 28,
    deck: 'SCENE_ON_HAI',
    title: 'MONSOON HAS ENTERED THE CHAT',
    urduTitle: 'مون سون بارشیں',
    description: "It's monsoon season. Your homes got caught in urban flooding.",
    actionText: 'PAY Rs 25 PER HOUSE & Rs 50 PER HOTEL FOR REPAIRS',
    illustration: '🌧️',
    actionType: 'PER_BUILDING_ASSESSMENT',
    perHouseCost: 25,
    perHotelCost: 50,
  },
  // Card 29 - Building Assessment
  {
    id: 29,
    deck: 'PAKISTAN_ZINDABAD',
    title: 'BHAI WANTS HIS HISSA',
    urduTitle: 'بھائی کا حصہ',
    description: 'You lost the court case. Now your brother demands his share.',
    actionText: 'PAY Rs 25 PER HOUSE & Rs 50 PER HOTEL',
    illustration: '👨‍👦',
    actionType: 'PER_BUILDING_ASSESSMENT',
    perHouseCost: 25,
    perHotelCost: 50,
  },
];
