import { GameSettings, BotPersonality } from './types';

export const DEFAULT_GAME_SETTINGS: GameSettings = {
  startingMoney: 1500,
  salaryOnStart: 200,
  auctionsEnabled: true,
  forcedAuctions: false,
  mortgagesEnabled: true,
  mortgageInterest: 0.10,
  evenBuild: true,
  freeParkingMode: 'NONE',
  freeParkingAmount: 100,
  maxJailTurns: 3,
  jailBail: 50,
  doublesExtraTurn: true,
  tripleDoublesJail: true,
  housesAvailable: 32,
  hotelsAvailable: 12,
  housesForHotel: 4,
  turnTimeoutSeconds: 45,
};

export const BOT_PERSONALITIES: BotPersonality[] = [
  {
    name: 'Plot Uncle 👴',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=PlotUncle',
    token: 'land_cruiser',
    tokenEmoji: '🚙',
    difficulty: 'HARD',
    tagline: 'Beta trust me, buy this plot. Rates are skyrocketing.',
    dialogues: {
      buy: ['Beta, investment in land never goes down!', 'Mubarak ho, file mere naam ho gayi!'],
      rentPaid: ['Wah, rent lenay ka tareeqa thora casual hai.', 'Yeh lo bhai, Agli baari meri hai.'],
      rentCollected: ['Shukriya beta, Har mahine time pe rent dena.', 'Paisa bolta hai!'],
      bankrupt: ['Abba nahi manenge... Mera plot chala gaya!', 'Real estate market crash ho gaya!'],
    },
  },
  {
    name: 'Lahori Burger 🍔',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=LahoriBurger',
    token: 'phone',
    tokenEmoji: '📱',
    difficulty: 'NORMAL',
    tagline: 'Bro Gulberg is vibes, let me build a cafe.',
    dialogues: {
      buy: ['OMG totally aesthetic plot bro!', 'DHA phase 99 coming soon guys!'],
      rentPaid: ['Bro wait, let me transfer via Sadapay.', 'So not cool!'],
      rentCollected: ['Cha-ching! Specialty coffee on me!', 'Thanks bro, stay aesthetic!'],
      bankrupt: ['Bro I am so broke rn... literal bankruptcy.', 'Going back to Defense.'],
    },
  },
  {
    name: 'WAPDA Inspector ⚡',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=WapdaInspector',
    token: 'chai_cup',
    tokenEmoji: '☕',
    difficulty: 'NORMAL',
    tagline: 'Meter check kar lo, transformer trip hone wala hai.',
    dialogues: {
      buy: ['Government land acquired for power grid!', 'Sub-station banega yahan.'],
      rentPaid: ['Surcharge lag gaya mere pe.', 'Line cut na kar dena.'],
      rentCollected: ['Bijli ka bill collect ho gaya!', 'Peak hours tariff applied.'],
      bankrupt: ['Grid fail ho gaya... Zero balance!', 'Load shedding permanent ho gayi.'],
    },
  },
  {
    name: 'Charsi Tikka Boss 🍗',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=CharsiTikka',
    token: 'chappal',
    tokenEmoji: '🩴',
    difficulty: 'EASY',
    tagline: 'Namak Mandi ki dukan hai, rozi khuli hai.',
    dialogues: {
      buy: ['Dumba karahi setup yahan lagega!', 'Zameen pakki, sauda naqad.'],
      rentPaid: ['Peshawari dosti mein sab chalta hai.', 'Chalo koylay ka kharcha nikal gaya.'],
      rentCollected: ['Kabab aur karahi ka bill clear karo!', 'Rosh tayar hai.'],
      bankrupt: ['Hotel par sealing lag gayi...', 'Dukan band, chalo wapis Saddar.'],
    },
  },
  {
    name: 'Raja Sahab 👑',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=RajaSahab',
    token: 'motorcycle',
    tokenEmoji: '🏍️',
    difficulty: 'HARD',
    tagline: 'Rawalpindi se Islamabad tak sirf apna raaj hai.',
    dialogues: {
      buy: ['Pindora se F-7 tak sab apna hai!', 'Sauda done, registry mere haath mein.'],
      rentPaid: ['Chota mota kharcha hai, koi masla nahi.', 'Raja sahab kabhi udhar nahi rakhte.'],
      rentCollected: ['Dabbang entry! Haqooq clear karo.', 'Raja ka tax ada karo!'],
      bankrupt: ['Izzat ka sauda nahi hota... Phir ayenge!', 'Paisa gaya, shaan baqi hai!'],
    },
  },
];
