import { BoardSpace, CityGroup } from './types.js';

export const CITY_GROUP_COLORS: Record<CityGroup, { hex: string; name: string; monument: string }> = {
  RAWALPINDI: { hex: '#7c3aed', name: 'Rawalpindi', monument: 'Liaquat Bagh' },
  LAHORE: { hex: '#38bdf8', name: 'Lahore', monument: 'Minar-e-Pakistan' },
  PESHAWAR: { hex: '#f472b6', name: 'Peshawar', monument: 'Bab-e-Khyber' },
  MULTAN: { hex: '#fb923c', name: 'Multan', monument: 'Rukn-e-Alam Tomb' },
  FAISALABAD: { hex: '#ef4444', name: 'Faisalabad', monument: 'Ghanta Ghar' },
  MURREE: { hex: '#facc15', name: 'Murree', monument: 'Mall Road Murree' },
  KARACHI: { hex: '#22c55e', name: 'Karachi', monument: 'Mazar-e-Quaid' },
  ISLAMABAD: { hex: '#2563eb', name: 'Islamabad', monument: 'Faisal Mosque' },
};

export const BOARD_SPACES: BoardSpace[] = [
  // 0: START
  {
    index: 0,
    name: 'START',
    type: 'START',
    icon: '💵',
    description: 'Collect 200 salary as you pass or land here.',
  },
  // 1: Brown 1
  {
    index: 1,
    name: 'Pindora',
    type: 'PROPERTY',
    cityGroup: 'RAWALPINDI',
    colorHex: '#7c3aed',
    price: 60,
    rent: 2,
    rentWithSet: 4,
    rentWith1House: 10,
    rentWith2Houses: 30,
    rentWith3Houses: 90,
    rentWith4Houses: 160,
    rentWithHotel: 250,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 30,
    description: 'Affordable Rawalpindi neighborhood.',
  },
  // 2: Card 1
  {
    index: 2,
    name: 'SCENE ON HAI',
    type: 'CARD_SCENE_ON_HAI',
    icon: '⚡',
    description: 'Draw a Scene On Hai card.',
  },
  // 3: Brown 2
  {
    index: 3,
    name: 'Raja Bazaar',
    type: 'PROPERTY',
    cityGroup: 'RAWALPINDI',
    colorHex: '#7c3aed',
    price: 60,
    rent: 4,
    rentWithSet: 8,
    rentWith1House: 20,
    rentWith2Houses: 60,
    rentWith3Houses: 180,
    rentWith4Houses: 320,
    rentWithHotel: 450,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 30,
    description: 'Historic vibrant market in Rawalpindi.',
  },
  // 4: Tax 1
  {
    index: 4,
    name: 'FBR TAX',
    type: 'TAX',
    icon: '📋',
    taxAmount: 200,
    description: 'Pay 200 Income Tax.',
  },
  // 5: Transport 1
  {
    index: 5,
    name: 'Metro Bus',
    type: 'TRANSPORT',
    icon: '🚌',
    price: 200,
    rent: 25,
    transportIndex: 0,
    mortgageValue: 100,
    description: 'High speed city transit.',
  },
  // 6: Light Blue 1
  {
    index: 6,
    name: 'Saddar',
    type: 'PROPERTY',
    cityGroup: 'LAHORE',
    colorHex: '#38bdf8',
    price: 100,
    rent: 6,
    rentWithSet: 12,
    rentWith1House: 30,
    rentWith2Houses: 90,
    rentWith3Houses: 270,
    rentWith4Houses: 400,
    rentWithHotel: 550,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 50,
    description: 'Commercial heart of Lahore Cantt.',
  },
  // 7: Card 2
  {
    index: 7,
    name: 'PAKISTAN ZINDABAD',
    type: 'CARD_PAKISTAN_ZINDABAD',
    icon: '🇵🇰',
    description: 'Draw a Pakistan Zindabad card.',
  },
  // 8: Light Blue 2
  {
    index: 8,
    name: 'Anarkali',
    type: 'PROPERTY',
    cityGroup: 'LAHORE',
    colorHex: '#38bdf8',
    price: 100,
    rent: 6,
    rentWithSet: 12,
    rentWith1House: 30,
    rentWith2Houses: 90,
    rentWith3Houses: 270,
    rentWith4Houses: 400,
    rentWithHotel: 550,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 50,
    description: 'Iconic heritage market of Lahore.',
  },
  // 9: Light Blue 3
  {
    index: 9,
    name: 'Mall Road',
    type: 'PROPERTY',
    cityGroup: 'LAHORE',
    colorHex: '#38bdf8',
    price: 120,
    rent: 8,
    rentWithSet: 16,
    rentWith1House: 40,
    rentWith2Houses: 100,
    rentWith3Houses: 300,
    rentWith4Houses: 450,
    rentWithHotel: 600,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 60,
    description: 'Prestigious boulevard in Lahore.',
  },
  // 10: Jail
  {
    index: 10,
    name: 'THANA / QUETTA CAFE',
    type: 'JAIL',
    icon: '☕',
    description: 'Visiting Quetta Cafe or Locked in Thana.',
  },
  // 11: Pink 1
  {
    index: 11,
    name: 'University Rd',
    type: 'PROPERTY',
    cityGroup: 'PESHAWAR',
    colorHex: '#f472b6',
    price: 140,
    rent: 10,
    rentWithSet: 20,
    rentWith1House: 50,
    rentWith2Houses: 150,
    rentWith3Houses: 450,
    rentWith4Houses: 625,
    rentWithHotel: 750,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 70,
    description: 'Main commercial corridor in Peshawar.',
  },
  // 12: Utility 1
  {
    index: 12,
    name: 'WAPDA',
    type: 'UTILITY',
    icon: '⚡',
    utilityType: 'WAPDA',
    price: 150,
    rent: 10,
    mortgageValue: 75,
    description: 'National electricity grid utility.',
  },
  // 13: Pink 2
  {
    index: 13,
    name: 'Hayatabad',
    type: 'PROPERTY',
    cityGroup: 'PESHAWAR',
    colorHex: '#f472b6',
    price: 140,
    rent: 10,
    rentWithSet: 20,
    rentWith1House: 50,
    rentWith2Houses: 150,
    rentWith3Houses: 450,
    rentWith4Houses: 625,
    rentWithHotel: 750,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 70,
    description: 'Modern township in Peshawar.',
  },
  // 14: Pink 3
  {
    index: 14,
    name: 'Karkhano',
    type: 'PROPERTY',
    cityGroup: 'PESHAWAR',
    colorHex: '#f472b6',
    price: 160,
    rent: 12,
    rentWithSet: 24,
    rentWith1House: 60,
    rentWith2Houses: 180,
    rentWith3Houses: 500,
    rentWith4Houses: 700,
    rentWithHotel: 900,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 80,
    description: 'Famed border trade market.',
  },
  // 15: Transport 2
  {
    index: 15,
    name: 'Rawal Express',
    type: 'TRANSPORT',
    icon: '🚂',
    price: 200,
    rent: 25,
    transportIndex: 1,
    mortgageValue: 100,
    description: 'Intercity high-speed train.',
  },
  // 16: Orange 1
  {
    index: 16,
    name: 'Cantt',
    type: 'PROPERTY',
    cityGroup: 'MULTAN',
    colorHex: '#fb923c',
    price: 180,
    rent: 14,
    rentWithSet: 28,
    rentWith1House: 70,
    rentWith2Houses: 200,
    rentWith3Houses: 550,
    rentWith4Houses: 750,
    rentWithHotel: 950,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 90,
    description: 'Prime Multan Cantonment area.',
  },
  // 17: Card 3
  {
    index: 17,
    name: 'SCENE ON HAI',
    type: 'CARD_SCENE_ON_HAI',
    icon: '⚡',
    description: 'Draw a Scene On Hai card.',
  },
  // 18: Orange 2
  {
    index: 18,
    name: 'Gulgasht',
    type: 'PROPERTY',
    cityGroup: 'MULTAN',
    colorHex: '#fb923c',
    price: 180,
    rent: 14,
    rentWithSet: 28,
    rentWith1House: 70,
    rentWith2Houses: 200,
    rentWith3Houses: 550,
    rentWith4Houses: 750,
    rentWithHotel: 950,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 90,
    description: 'Bustling commercial zone in Multan.',
  },
  // 19: Orange 3
  {
    index: 19,
    name: 'Bosan Road',
    type: 'PROPERTY',
    cityGroup: 'MULTAN',
    colorHex: '#fb923c',
    price: 200,
    rent: 16,
    rentWithSet: 32,
    rentWith1House: 80,
    rentWith2Houses: 220,
    rentWith3Houses: 600,
    rentWith4Houses: 800,
    rentWithHotel: 1000,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 100,
    description: 'Major educational and commercial hub.',
  },
  // 20: Free Parking
  {
    index: 20,
    name: 'HIRA MANDI',
    type: 'FREE_PARKING',
    icon: '🎭',
    description: 'Free Parking & Rest Zone.',
  },
  // 21: Red 1
  {
    index: 21,
    name: 'D Ground',
    type: 'PROPERTY',
    cityGroup: 'FAISALABAD',
    colorHex: '#ef4444',
    price: 220,
    rent: 18,
    rentWithSet: 36,
    rentWith1House: 90,
    rentWith2Houses: 250,
    rentWith3Houses: 700,
    rentWith4Houses: 875,
    rentWithHotel: 1050,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 110,
    description: 'Vibrant commercial hub of Faisalabad.',
  },
  // 22: Card 4
  {
    index: 22,
    name: 'PAKISTAN ZINDABAD',
    type: 'CARD_PAKISTAN_ZINDABAD',
    icon: '🇵🇰',
    description: 'Draw a Pakistan Zindabad card.',
  },
  // 23: Red 2
  {
    index: 23,
    name: 'Clock Tower',
    type: 'PROPERTY',
    cityGroup: 'FAISALABAD',
    colorHex: '#ef4444',
    price: 220,
    rent: 18,
    rentWithSet: 36,
    rentWith1House: 90,
    rentWith2Houses: 250,
    rentWith3Houses: 700,
    rentWith4Houses: 875,
    rentWithHotel: 1050,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 110,
    description: 'Historic city center of Faisalabad.',
  },
  // 24: Red 3
  {
    index: 24,
    name: 'Kohinoor',
    type: 'PROPERTY',
    cityGroup: 'FAISALABAD',
    colorHex: '#ef4444',
    price: 240,
    rent: 20,
    rentWithSet: 40,
    rentWith1House: 100,
    rentWith2Houses: 300,
    rentWith3Houses: 750,
    rentWith4Houses: 925,
    rentWithHotel: 1100,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 120,
    description: 'Upscale market plaza in Faisalabad.',
  },
  // 25: Transport 3
  {
    index: 25,
    name: 'Shalimar',
    type: 'TRANSPORT',
    icon: '🚂',
    price: 200,
    rent: 25,
    transportIndex: 2,
    mortgageValue: 100,
    description: 'Express Railway service.',
  },
  // 26: Yellow 1
  {
    index: 26,
    name: 'Mall Rd',
    type: 'PROPERTY',
    cityGroup: 'MURREE',
    colorHex: '#facc15',
    price: 260,
    rent: 22,
    rentWithSet: 44,
    rentWith1House: 110,
    rentWith2Houses: 330,
    rentWith3Houses: 800,
    rentWith4Houses: 975,
    rentWithHotel: 1150,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 130,
    description: 'Tourist hotspot in Murree Hills.',
  },
  // 27: Yellow 2
  {
    index: 27,
    name: 'Patriata',
    type: 'PROPERTY',
    cityGroup: 'MURREE',
    colorHex: '#facc15',
    price: 260,
    rent: 22,
    rentWithSet: 44,
    rentWith1House: 110,
    rentWith2Houses: 330,
    rentWith3Houses: 800,
    rentWith4Houses: 975,
    rentWithHotel: 1150,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 130,
    description: 'Scenic hill resort and chairlift.',
  },
  // 28: Utility 2
  {
    index: 28,
    name: 'Sui Gas',
    type: 'UTILITY',
    icon: '🔥',
    utilityType: 'SUI_GAS',
    price: 150,
    rent: 10,
    mortgageValue: 75,
    description: 'Natural gas utility provider.',
  },
  // 29: Yellow 3
  {
    index: 29,
    name: 'Bhurban',
    type: 'PROPERTY',
    cityGroup: 'MURREE',
    colorHex: '#facc15',
    price: 280,
    rent: 24,
    rentWithSet: 48,
    rentWith1House: 120,
    rentWith2Houses: 360,
    rentWith3Houses: 850,
    rentWith4Houses: 1025,
    rentWithHotel: 1200,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 140,
    description: '5-star luxury hill resort.',
  },
  // 30: Go to Jail
  {
    index: 30,
    name: 'MET A LAHORI',
    type: 'GO_TO_JAIL',
    icon: '🚨',
    description: 'Followed wrong directions. Go to Thana!',
  },
  // 31: Green 1
  {
    index: 31,
    name: 'Clifton',
    type: 'PROPERTY',
    cityGroup: 'KARACHI',
    colorHex: '#22c55e',
    price: 300,
    rent: 26,
    rentWithSet: 52,
    rentWith1House: 130,
    rentWith2Houses: 390,
    rentWith3Houses: 900,
    rentWith4Houses: 1100,
    rentWithHotel: 1275,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 150,
    description: 'Seaside upscale district in Karachi.',
  },
  // 32: Green 2
  {
    index: 32,
    name: 'Defence',
    type: 'PROPERTY',
    cityGroup: 'KARACHI',
    colorHex: '#22c55e',
    price: 300,
    rent: 26,
    rentWithSet: 52,
    rentWith1House: 130,
    rentWith2Houses: 390,
    rentWith3Houses: 900,
    rentWith4Houses: 1100,
    rentWithHotel: 1275,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 150,
    description: 'Elite residential enclave in Karachi.',
  },
  // 33: Card 5
  {
    index: 33,
    name: 'SCENE ON HAI',
    type: 'CARD_SCENE_ON_HAI',
    icon: '⚡',
    description: 'Draw a Scene On Hai card.',
  },
  // 34: Green 3
  {
    index: 34,
    name: 'Gulberg',
    type: 'PROPERTY',
    cityGroup: 'KARACHI',
    colorHex: '#22c55e',
    price: 320,
    rent: 28,
    rentWithSet: 56,
    rentWith1House: 150,
    rentWith2Houses: 450,
    rentWith3Houses: 1000,
    rentWith4Houses: 1200,
    rentWithHotel: 1400,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 160,
    description: 'High-density commercial center.',
  },
  // 35: Transport 4
  {
    index: 35,
    name: 'Karachi Exp',
    type: 'TRANSPORT',
    icon: '🚂',
    price: 200,
    rent: 25,
    transportIndex: 3,
    mortgageValue: 100,
    description: 'Port city railway connection.',
  },
  // 36: Card 6
  {
    index: 36,
    name: 'PAKISTAN ZINDABAD',
    type: 'CARD_PAKISTAN_ZINDABAD',
    icon: '🇵🇰',
    description: 'Draw a Pakistan Zindabad card.',
  },
  // 37: Dark Blue 1
  {
    index: 37,
    name: 'Blue Area',
    type: 'PROPERTY',
    cityGroup: 'ISLAMABAD',
    colorHex: '#2563eb',
    price: 350,
    rent: 35,
    rentWithSet: 70,
    rentWith1House: 175,
    rentWith2Houses: 500,
    rentWith3Houses: 1100,
    rentWith4Houses: 1300,
    rentWithHotel: 1500,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 175,
    description: 'Federal capital financial corridor.',
  },
  // 38: Tax 2
  {
    index: 38,
    name: 'VIP TAX',
    type: 'TAX',
    icon: '💎',
    taxAmount: 100,
    description: 'Pay 100 VIP Protocol Tax.',
  },
  // 39: Dark Blue 2
  {
    index: 39,
    name: 'F-6',
    type: 'PROPERTY',
    cityGroup: 'ISLAMABAD',
    colorHex: '#2563eb',
    price: 400,
    rent: 50,
    rentWithSet: 100,
    rentWith1House: 200,
    rentWith2Houses: 600,
    rentWith3Houses: 1400,
    rentWith4Houses: 1700,
    rentWithHotel: 2000,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 200,
    description: 'Most exclusive diplomatic enclave.',
  },
];

export const CITY_GROUP_MEMBERS: Record<CityGroup, number[]> = {
  RAWALPINDI: [1, 3],
  LAHORE: [6, 8, 9],
  PESHAWAR: [11, 13, 14],
  MULTAN: [16, 18, 19],
  FAISALABAD: [21, 23, 24],
  MURREE: [26, 27, 29],
  KARACHI: [31, 32, 34],
  ISLAMABAD: [37, 39],
};

export const TRANSPORT_SPACES = [5, 15, 25, 35];
export const UTILITY_SPACES = [12, 28];
