import { BoardSpace, CityGroup } from './types';

export const CITY_GROUP_COLORS: Record<CityGroup, { hex: string; name: string; border: string; bg: string }> = {
  RAWALPINDI: { hex: '#8B4513', name: 'Rawalpindi', border: 'border-amber-900', bg: 'bg-amber-900' },
  LAHORE: { hex: '#38BDF8', name: 'Lahore', border: 'border-sky-400', bg: 'bg-sky-400' },
  PESHAWAR: { hex: '#F472B6', name: 'Peshawar', border: 'border-pink-400', bg: 'bg-pink-400' },
  MULTAN: { hex: '#FB923C', name: 'Multan', border: 'border-orange-400', bg: 'bg-orange-400' },
  FAISALABAD: { hex: '#EF4444', name: 'Faisalabad', border: 'border-red-500', bg: 'bg-red-500' },
  MURREE: { hex: '#FACC15', name: 'Murree', border: 'border-yellow-400', bg: 'bg-yellow-400' },
  KARACHI: { hex: '#22C55E', name: 'Karachi', border: 'border-green-500', bg: 'bg-green-500' },
  ISLAMABAD: { hex: '#1E40AF', name: 'Islamabad', border: 'border-blue-700', bg: 'bg-blue-700' },
};

export const BOARD_SPACES: BoardSpace[] = [
  // 0: START
  {
    index: 0,
    name: 'SALARY AA GAYI',
    urduName: 'تنخواہ آ گئی',
    type: 'START',
    icon: '💵',
    description: 'Collect Rs 200 salary as you pass or land here.',
  },
  // 1: Brown 1
  {
    index: 1,
    name: 'Pindora',
    urduName: 'پنڈورا',
    type: 'PROPERTY',
    cityGroup: 'RAWALPINDI',
    colorHex: '#8B4513',
    price: 60,
    rent: 2,
    rentWithSet: 4,
    rentWith1House: 10,
    rentWith2Houses: 30,
    rentWith3Houses: 90,
    rentWith4Houses: 160,
    rentWithHotel: 250,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 30,
    description: 'Busy Rawalpindi neighborhood. Affordable plot.',
  },
  // 2: Card 1
  {
    index: 2,
    name: 'SCENE ON HAI',
    urduName: 'سین آن ہے',
    type: 'CARD_SCENE_ON_HAI',
    icon: '😂',
    description: 'Draw a Scene On Hai Pakistani chaos card.',
  },
  // 3: Brown 2
  {
    index: 3,
    name: 'Raja Bazaar',
    urduName: 'راجہ بازار',
    type: 'PROPERTY',
    cityGroup: 'RAWALPINDI',
    colorHex: '#8B4513',
    price: 60,
    rent: 4,
    rentWithSet: 8,
    rentWith1House: 20,
    rentWith2Houses: 60,
    rentWith3Houses: 180,
    rentWith4Houses: 320,
    rentWithHotel: 450,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 30,
    description: 'Historic vibrant market in the heart of Rawalpindi.',
  },
  // 4: Tax 1
  {
    index: 4,
    name: 'FBR TAX',
    urduName: 'ایف بی آر ٹیکس',
    type: 'TAX',
    taxAmount: 200,
    icon: '📋',
    description: 'Audit time! Pay Rs 200 to the bank.',
  },
  // 5: Transport 1
  {
    index: 5,
    name: 'Lahore Junction',
    urduName: 'لاہور جنکشن',
    type: 'TRANSPORT',
    transportIndex: 0,
    price: 200,
    rent: 25,
    mortgageValue: 100,
    icon: '🚂',
    description: 'Rent: 1 train = Rs 25, 2 = Rs 50, 3 = Rs 100, 4 = Rs 200.',
  },
  // 6: Light Blue 1
  {
    index: 6,
    name: 'Gulberg',
    urduName: 'گلبرگ',
    type: 'PROPERTY',
    cityGroup: 'LAHORE',
    colorHex: '#38BDF8',
    price: 100,
    rent: 6,
    rentWithSet: 12,
    rentWith1House: 30,
    rentWith2Houses: 90,
    rentWith3Houses: 270,
    rentWith4Houses: 400,
    rentWithHotel: 550,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 50,
    description: 'Prime commercial and residential hotspot in Lahore.',
  },
  // 7: Card 2
  {
    index: 7,
    name: 'PAKISTAN ZINDABAD',
    urduName: 'پاکستان زندہ باد',
    type: 'CARD_PAKISTAN_ZINDABAD',
    icon: '🇵🇰',
    description: 'Draw a Pakistan Zindabad event card.',
  },
  // 8: Light Blue 2
  {
    index: 8,
    name: 'Liberty',
    urduName: 'لبرٹی مارکیٹ',
    type: 'PROPERTY',
    cityGroup: 'LAHORE',
    colorHex: '#38BDF8',
    price: 100,
    rent: 6,
    rentWithSet: 12,
    rentWith1House: 30,
    rentWith2Houses: 90,
    rentWith3Houses: 270,
    rentWith4Houses: 400,
    rentWithHotel: 550,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 50,
    description: 'Iconic shopping round-about in Lahore.',
  },
  // 9: Light Blue 3
  {
    index: 9,
    name: 'MM Alam Road',
    urduName: 'ایم ایم عالم روڈ',
    type: 'PROPERTY',
    cityGroup: 'LAHORE',
    colorHex: '#38BDF8',
    price: 120,
    rent: 8,
    rentWithSet: 16,
    rentWith1House: 40,
    rentWith2Houses: 100,
    rentWith3Houses: 300,
    rentWith4Houses: 450,
    rentWithHotel: 600,
    houseCost: 50,
    hotelCost: 50,
    mortgageValue: 60,
    description: 'The food street of the elites.',
  },
  // 10: JAIL / JUST VISITING
  {
    index: 10,
    name: 'THANA / QUETTA CAFÉ',
    urduName: 'تھانہ / کوئٹہ کیفے',
    type: 'JAIL',
    icon: '☕',
    description: 'Thana (Jail) or Just Visiting for a cup of Karak Chai at Quetta Café.',
  },
  // 11: Pink 1
  {
    index: 11,
    name: 'Saddar',
    urduName: 'صدر پشاور',
    type: 'PROPERTY',
    cityGroup: 'PESHAWAR',
    colorHex: '#F472B6',
    price: 140,
    rent: 10,
    rentWithSet: 20,
    rentWith1House: 50,
    rentWith2Houses: 150,
    rentWith3Houses: 450,
    rentWith4Houses: 625,
    rentWithHotel: 750,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 70,
    description: 'Peshawar central commerce and Chapli Kebab hub.',
  },
  // 12: Utility 1
  {
    index: 12,
    name: 'WAPDA',
    urduName: 'واپڈا',
    type: 'UTILITY',
    utilityType: 'WAPDA',
    price: 150,
    mortgageValue: 75,
    icon: '⚡',
    description: 'Rent is 4x dice roll (or 10x if both utilities owned).',
  },
  // 13: Pink 2
  {
    index: 13,
    name: 'University Town',
    urduName: 'یونیورسٹی ٹاؤن',
    type: 'PROPERTY',
    cityGroup: 'PESHAWAR',
    colorHex: '#F472B6',
    price: 140,
    rent: 10,
    rentWithSet: 20,
    rentWith1House: 50,
    rentWith2Houses: 150,
    rentWith3Houses: 450,
    rentWith4Houses: 625,
    rentWithHotel: 750,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 70,
    description: 'Elite peaceful living and sprawling greenery.',
  },
  // 14: Pink 3
  {
    index: 14,
    name: 'Hayatabad',
    urduName: 'حیات آباد',
    type: 'PROPERTY',
    cityGroup: 'PESHAWAR',
    colorHex: '#F472B6',
    price: 160,
    rent: 12,
    rentWithSet: 24,
    rentWith1House: 60,
    rentWith2Houses: 180,
    rentWith3Houses: 500,
    rentWith4Houses: 700,
    rentWithHotel: 900,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 80,
    description: 'Modern planned township overlooking Khyber.',
  },
  // 15: Transport 2
  {
    index: 15,
    name: 'Rawalpindi Station',
    urduName: 'راولپنڈی ریلوے اسٹیشن',
    type: 'TRANSPORT',
    transportIndex: 1,
    price: 200,
    rent: 25,
    mortgageValue: 100,
    icon: '🚂',
    description: 'Rent: 1 train = Rs 25, 2 = Rs 50, 3 = Rs 100, 4 = Rs 200.',
  },
  // 16: Orange 1
  {
    index: 16,
    name: 'Hussain Agahi',
    urduName: 'حسین آگاہی',
    type: 'PROPERTY',
    cityGroup: 'MULTAN',
    colorHex: '#FB923C',
    price: 180,
    rent: 14,
    rentWithSet: 28,
    rentWith1House: 70,
    rentWith2Houses: 200,
    rentWith3Houses: 550,
    rentWith4Houses: 750,
    rentWithHotel: 950,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 90,
    description: 'City of saints, sohan halwa, and bustling bazaars.',
  },
  // 17: Card 3
  {
    index: 17,
    name: 'SCENE ON HAI',
    urduName: 'سین آن ہے',
    type: 'CARD_SCENE_ON_HAI',
    icon: '😂',
    description: 'Draw a Scene On Hai Pakistani chaos card.',
  },
  // 18: Orange 2
  {
    index: 18,
    name: 'Gulgasht',
    urduName: 'گلگشت کالونی',
    type: 'PROPERTY',
    cityGroup: 'MULTAN',
    colorHex: '#FB923C',
    price: 180,
    rent: 14,
    rentWithSet: 28,
    rentWith1House: 70,
    rentWith2Houses: 200,
    rentWith3Houses: 550,
    rentWith4Houses: 750,
    rentWithHotel: 950,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 90,
    description: 'The fashion and cafe hub of Multan.',
  },
  // 19: Orange 3
  {
    index: 19,
    name: 'Cantt',
    urduName: 'کینٹ ملتان',
    type: 'PROPERTY',
    cityGroup: 'MULTAN',
    colorHex: '#FB923C',
    price: 200,
    rent: 16,
    rentWithSet: 32,
    rentWith1House: 80,
    rentWith2Houses: 220,
    rentWith3Houses: 600,
    rentWith4Houses: 800,
    rentWithHotel: 1000,
    houseCost: 100,
    hotelCost: 100,
    mortgageValue: 100,
    description: 'Wide roads, golf course, and prestigious plots.',
  },
  // 20: FREE PARKING
  {
    index: 20,
    name: 'HIRA MANDI',
    urduName: 'ہیرا منڈی',
    type: 'FREE_PARKING',
    icon: '🎭',
    description: 'Free parking / Cultural rest space. Relax without paying rent.',
  },
  // 21: Red 1
  {
    index: 21,
    name: 'D-Ground',
    urduName: 'ڈی گراؤنڈ',
    type: 'PROPERTY',
    cityGroup: 'FAISALABAD',
    colorHex: '#EF4444',
    price: 220,
    rent: 18,
    rentWithSet: 36,
    rentWith1House: 90,
    rentWith2Houses: 250,
    rentWith3Houses: 700,
    rentWith4Houses: 875,
    rentWithHotel: 1050,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 110,
    description: 'Faisalabad premier commercial round plaza.',
  },
  // 22: Card 4
  {
    index: 22,
    name: 'PAKISTAN ZINDABAD',
    urduName: 'پاکستان زندہ باد',
    type: 'CARD_PAKISTAN_ZINDABAD',
    icon: '🇵🇰',
    description: 'Draw a Pakistan Zindabad event card.',
  },
  // 23: Red 2
  {
    index: 23,
    name: 'Susan Road',
    urduName: 'سوسن روڈ',
    type: 'PROPERTY',
    cityGroup: 'FAISALABAD',
    colorHex: '#EF4444',
    price: 220,
    rent: 18,
    rentWithSet: 36,
    rentWith1House: 90,
    rentWith2Houses: 250,
    rentWith3Houses: 700,
    rentWith4Houses: 875,
    rentWithHotel: 1050,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 110,
    description: 'Textile money and bustling retail avenue.',
  },
  // 24: Red 3
  {
    index: 24,
    name: 'Canal Road',
    urduName: 'کینال روڈ فیصل آباد',
    type: 'PROPERTY',
    cityGroup: 'FAISALABAD',
    colorHex: '#EF4444',
    price: 240,
    rent: 20,
    rentWithSet: 40,
    rentWith1House: 100,
    rentWith2Houses: 300,
    rentWith3Houses: 750,
    rentWith4Houses: 925,
    rentWithHotel: 1100,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 120,
    description: 'Express highway lined with mansions and mills.',
  },
  // 25: Transport 3
  {
    index: 25,
    name: 'Karachi Cantt',
    urduName: 'کراچی کینٹ اسٹیشن',
    type: 'TRANSPORT',
    transportIndex: 2,
    price: 200,
    rent: 25,
    mortgageValue: 100,
    icon: '🚂',
    description: 'Rent: 1 train = Rs 25, 2 = Rs 50, 3 = Rs 100, 4 = Rs 200.',
  },
  // 26: Yellow 1
  {
    index: 26,
    name: 'Mall Road',
    urduName: 'مال روڈ مری',
    type: 'PROPERTY',
    cityGroup: 'MURREE',
    colorHex: '#FACC15',
    price: 260,
    rent: 22,
    rentWithSet: 44,
    rentWith1House: 110,
    rentWith2Houses: 330,
    rentWith3Houses: 800,
    rentWith4Houses: 975,
    rentWithHotel: 1150,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 130,
    description: 'Snow, coffee, tourists, and prime mountain retail.',
  },
  // 27: Yellow 2
  {
    index: 27,
    name: 'Kashmir Point',
    urduName: 'کشمیر پوائنٹ',
    type: 'PROPERTY',
    cityGroup: 'MURREE',
    colorHex: '#FACC15',
    price: 260,
    rent: 22,
    rentWithSet: 44,
    rentWith1House: 110,
    rentWith2Houses: 330,
    rentWith3Houses: 800,
    rentWith4Houses: 975,
    rentWithHotel: 1150,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 130,
    description: 'Scenic high-altitude luxury retreats.',
  },
  // 28: Utility 2
  {
    index: 28,
    name: 'Sui Gas',
    urduName: 'سوئی گیس',
    type: 'UTILITY',
    utilityType: 'SUI_GAS',
    price: 150,
    mortgageValue: 75,
    icon: '🔥',
    description: 'Rent is 4x dice roll (or 10x if both utilities owned).',
  },
  // 29: Yellow 3
  {
    index: 29,
    name: 'Pindi Point',
    urduName: 'پنڈی پوائنٹ',
    type: 'PROPERTY',
    cityGroup: 'MURREE',
    colorHex: '#FACC15',
    price: 280,
    rent: 24,
    rentWithSet: 48,
    rentWith1House: 120,
    rentWith2Houses: 360,
    rentWith3Houses: 850,
    rentWith4Houses: 1025,
    rentWithHotel: 1200,
    houseCost: 150,
    hotelCost: 150,
    mortgageValue: 140,
    description: 'Chairlifts, Pine forests, and high tourist rents.',
  },
  // 30: GO TO JAIL
  {
    index: 30,
    name: 'MET A LAHORI, WENT THE WRONG WAY',
    urduName: 'لاہوری سے راستہ پوچھا، غلط چلے گئے',
    type: 'GO_TO_JAIL',
    icon: '🚔',
    description: 'You asked a Lahori for directions. Went the wrong way straight to THANA!',
  },
  // 31: Green 1
  {
    index: 31,
    name: 'Clifton',
    urduName: 'کلفٹن',
    type: 'PROPERTY',
    cityGroup: 'KARACHI',
    colorHex: '#22C55E',
    price: 300,
    rent: 26,
    rentWithSet: 52,
    rentWith1House: 130,
    rentWith2Houses: 390,
    rentWith3Houses: 900,
    rentWith4Houses: 1100,
    rentWithHotel: 1275,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 150,
    description: 'Sea breeze, malls, and Karachi high society.',
  },
  // 32: Green 2
  {
    index: 32,
    name: 'PECHS',
    urduName: 'پی ای سی ایچ ایس',
    type: 'PROPERTY',
    cityGroup: 'KARACHI',
    colorHex: '#22C55E',
    price: 300,
    rent: 26,
    rentWithSet: 52,
    rentWith1House: 130,
    rentWith2Houses: 390,
    rentWith3Houses: 900,
    rentWith4Houses: 1100,
    rentWithHotel: 1275,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 150,
    description: 'Central Karachi commercial powerhouse on Tariq Road.',
  },
  // 33: Card 5
  {
    index: 33,
    name: 'SCENE ON HAI',
    urduName: 'سین آن ہے',
    type: 'CARD_SCENE_ON_HAI',
    icon: '😂',
    description: 'Draw a Scene On Hai Pakistani chaos card.',
  },
  // 34: Green 3
  {
    index: 34,
    name: 'DHA',
    urduName: 'ڈی ایچ اے کراچی',
    type: 'PROPERTY',
    cityGroup: 'KARACHI',
    colorHex: '#22C55E',
    price: 320,
    rent: 28,
    rentWithSet: 56,
    rentWith1House: 150,
    rentWith2Houses: 450,
    rentWith3Houses: 1000,
    rentWith4Houses: 1200,
    rentWithHotel: 1400,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 160,
    description: 'Phase 8 sea-view properties, highest Karachi prestige.',
  },
  // 35: Transport 4
  {
    index: 35,
    name: 'Peshawar Cantt',
    urduName: 'پشاور کینٹ اسٹیشن',
    type: 'TRANSPORT',
    transportIndex: 3,
    price: 200,
    rent: 25,
    mortgageValue: 100,
    icon: '🚂',
    description: 'Rent: 1 train = Rs 25, 2 = Rs 50, 3 = Rs 100, 4 = Rs 200.',
  },
  // 36: Card 6
  {
    index: 36,
    name: 'PAKISTAN ZINDABAD',
    urduName: 'پاکستان زندہ باد',
    type: 'CARD_PAKISTAN_ZINDABAD',
    icon: '🇵🇰',
    description: 'Draw a Pakistan Zindabad event card.',
  },
  // 37: Dark Blue 1
  {
    index: 37,
    name: 'F-6',
    urduName: 'ایف سکس اسلام آباد',
    type: 'PROPERTY',
    cityGroup: 'ISLAMABAD',
    colorHex: '#1E40AF',
    price: 350,
    rent: 35,
    rentWithSet: 70,
    rentWith1House: 175,
    rentWith2Houses: 500,
    rentWith3Houses: 1100,
    rentWith4Houses: 1300,
    rentWithHotel: 1500,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 175,
    description: 'Super Market, diplomatic enclave borders, and Margalla views.',
  },
  // 38: Tax 2
  {
    index: 38,
    name: 'BIJLI SURCHARGE',
    urduName: 'بجلی سرچارج',
    type: 'TAX',
    taxAmount: 100,
    icon: '💡',
    description: 'Peak hour tariff & fuel adjustment! Pay Rs 100.',
  },
  // 39: Dark Blue 2
  {
    index: 39,
    name: 'F-7',
    urduName: 'ایف سیون اسلام آباد',
    type: 'PROPERTY',
    cityGroup: 'ISLAMABAD',
    colorHex: '#1E40AF',
    price: 400,
    rent: 50,
    rentWithSet: 100,
    rentWith1House: 200,
    rentWith2Houses: 600,
    rentWith3Houses: 1400,
    rentWith4Houses: 1700,
    rentWithHotel: 2000,
    houseCost: 200,
    hotelCost: 200,
    mortgageValue: 200,
    description: 'Jinnah Super! The ultimate Pakistani property flex.',
  },
];

export const CITY_GROUP_MEMBERS: Record<CityGroup, number[]> = {
  RAWALPINDI: [1, 3],
  LAHORE: [6, 8, 9],
  PESHAWAR: [11, 13, 14],
  MULTAN: [16, 18, 19],
  FAISALABAD: [21, 23, 24],
  MURREE: [26, 27, 29],
  KARACHI: [31, 32, 34],
  ISLAMABAD: [37, 39],
};

export const TRANSPORT_SPACES = [5, 15, 25, 35];
export const UTILITY_SPACES = [12, 28];
